/*
** Copyright 2014-2018 The Earlham Institute
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
/*
 * blast_service_job_markup_keys.h
 *
 *  Created on: 29 Jan 2019
 *      Author: billy
 */

#ifndef SERVICES_BLAST_SERVICE_INCLUDE_BLAST_SERVICE_JOB_MARKUP_KEYS_H_
#define SERVICES_BLAST_SERVICE_INCLUDE_BLAST_SERVICE_JOB_MARKUP_KEYS_H_

#include "blast_service_api.h"

#ifndef DOXYGEN_SHOULD_SKIP_THIS

#ifdef ALLOCATE_BLAST_SERVICE_JOB_MARKUP_KEYS_CONSTANTS
	#define BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX BLAST_SERVICE_LOCAL
	#define BLAST_SERVICE_JOB_MARKUP_KEYS_VAL(x)	= x
#else
	#define BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX extern
	#define BLAST_SERVICE_JOB_MARKUP_KEYS_VAL(x)
#endif

#endif 		/* #ifndef DOXYGEN_SHOULD_SKIP_THIS */


BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_REPORTS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("reports");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_RESULTS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("blast_search_results");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_REPORT_RESULTS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("hits");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_POLYMORPHISMS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("polymorphisms");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_HSPS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("hsps");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_SNP_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("snp");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_MNP_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("mnp");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_QUERY_SEQUENCE_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("query_sequence");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_LOCUS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("locus");

BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_FALDO_BEGIN_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("faldo:begin");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_FALDO_END_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("faldo:end");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_FALDO_POSITION_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("faldo:position");

BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_SCAFFOLDS_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("scaffolds");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_SCAFFOLD_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("scaffold");

BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_SEQUENCE_DIFFERENCE_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("sequence_difference");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_QUERY_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("query");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_HIT_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("hit");

BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_DATATBASE_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("database");
BLAST_SERVICE_JOB_MARKUP_KEYS_PREFIX const char *BSJMK_DATATBASE_NAME_S BLAST_SERVICE_JOB_MARKUP_KEYS_VAL ("database_name");


#endif /* SERVICES_BLAST_SERVICE_INCLUDE_BLAST_SERVICE_JOB_MARKUP_KEYS_H_ */
